name: cafebazaar_auth
description: With this package you can use CafeBazaar auth and storage in flutter applications, This package only supports Android applications.
version: 1.0.0
homepage: https://github.com/arsamme/flutter_cafebazaar_auth

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - packages/cafebazaar_auth/assets/images/bazaar.png

  plugin:
    platforms:
      android:
        package: me.arsam.cafebazaar_auth
        pluginClass: CafeBazaarAuthPlugin

